baseURL: "https://examplesite.com/"
title: LibreForte
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: LibreForte
    description: "Conhecimento Compartilhado"
    keywords: [Blog, Portfolio, PaperMod]
    author: Thiago Mendonça
    # author: ["Me", "You"] # multiple authors
    images: ["https://i.pinimg.com/736x/bc/39/bc/bc39bc7b135e5e7277aa7fc69f6aae36--supply-chain-blog-design.jpg"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "https://i.pinimg.com/736x/bc/39/bc/bc39bc7b135e5e7277aa7fc69f6aae36--supply-chain-blog-design.jpg"
        favicon16x16: "https://i.pinimg.com/736x/bc/39/bc/bc39bc7b135e5e7277aa7fc69f6aae36--supply-chain-blog-design.jpg"
        favicon32x32: "https://i.pinimg.com/736x/bc/39/bc/bc39bc7b135e5e7277aa7fc69f6aae36--supply-chain-blog-design.jpg"
        apple_touch_icon: "https://i.pinimg.com/736x/bc/39/bc/bc39bc7b135e5e7277aa7fc69f6aae36--supply-chain-blog-design.jpg"
        safari_pinned_tab: "https://i.pinimg.com/736x/bc/39/bc/bc39bc7b135e5e7277aa7fc69f6aae36--supply-chain-blog-design.jpg"

    label:
        text: "Home"
        icon: "https://i.pinimg.com/736x/bc/39/bc/bc39bc7b135e5e7277aa7fc69f6aae36--supply-chain-blog-design.jpg"
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: LibreForte
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Opa! \U0001F44B"
        Content: Seja bem vindo!

    #socialIcons:
    #    - name: twitter
    #      url: "https://twitter.com/"
    #    - name: stackoverflow
    #      url: "https://stackoverflow.com"
    #    - name: github
    #      url: "https://github.com/"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/<path_to_repo>/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        #- identifier: example
        #  name: example.org
        #  url: https://example.org
        #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
